## 1# Pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.0.1+cu118


## Creating Tensors

In [5]:
## Scalers

s1 = torch.tensor(10)
print(s1)

tensor(10)


In [8]:
s1.ndim

0

In [9]:
## Get number back as Python int
s1.item()

10

In [10]:
## Vector

v1 = torch.tensor([5, 5])
v1

tensor([5, 5])

In [11]:
v1.ndim

1

In [13]:
v1.shape

torch.Size([2])

In [24]:
## Matrix
M1 = torch.tensor([[7,8],
                   [9,10]])

M1

tensor([[ 7,  8],
        [ 9, 10]])

In [25]:
M1.ndim

2

In [26]:
M1[1]

tensor([ 9, 10])

In [27]:
M1.shape

torch.Size([2, 2])

In [28]:
## Tensor
T1 = torch.tensor([[[1,2,3],
                    [3,6,9],
                    [2,5,8]]])
T1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 8]]])

In [29]:
T1.ndim

3

In [30]:
T1.shape

torch.Size([1, 3, 3])

In [31]:
T1[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 8]])

# 2# Creating Random Tensors in PyTorch




In [35]:
randTensor1 = torch.rand(3,4)
randTensor1

tensor([[0.5726, 0.4453, 0.0361, 0.1992],
        [0.8599, 0.6979, 0.2107, 0.8545],
        [0.4955, 0.6324, 0.3434, 0.7691]])

In [36]:
randTensor1.ndim

2

In [37]:
randTensor2 = torch.rand(1,3,3)
randTensor2

tensor([[[0.7221, 0.4576, 0.6259],
         [0.2624, 0.2610, 0.9265],
         [0.9026, 0.2853, 0.2169]]])

In [38]:
randTensor2.ndim

3

In [40]:
## Create a random tensor similar to image shape

image_tensor = torch.rand(size=(512,512,3))
image_tensor
image_tensor.shape, image_tensor.ndim

(torch.Size([512, 512, 3]), 3)

# Creating Tensors With Zeros and Ones in PyTorch

In [41]:
# Create a tensor of all zeros
zeros = torch.zeros([3,4])
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
zeros * randTensor1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
# Create a tensor of all Ones

ones = torch.ones([3,4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [47]:
## Default datatype of pytorch tensor
ones.dtype

torch.float32

In [48]:
randTensor1.dtype

torch.float32