# 1# Introduction to Tensors

In [2]:
import torch
torch.__version__

'2.1.0+cu118'

In [3]:
#Scaler
s1 = torch.tensor(10)
print(s1)

tensor(10)


In [5]:
print(s1.ndim)
print(s1.item())

0
10


In [6]:
#Vector
vec1 = torch.tensor([10,10])
print(vec1)

tensor([10, 10])


In [10]:
print(vec1.ndim)
print(vec1.shape)
print(vec1.size())

1
torch.Size([2])
torch.Size([2])


In [12]:
#MATRIX
M1 = torch.tensor([[10,20,30],
                   [40,50,60],
                   [70,80,90]])
print(M1)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [15]:
print(M1.ndim)
print(M1.shape)
print(M1.size())

2
torch.Size([3, 3])
torch.Size([3, 3])


In [19]:
print(M1[0])
print(M1[0,1])

tensor([10, 20, 30])
tensor(20)


In [20]:
#ndim TENSOR
T1 = torch.tensor([[[1,2,3],
                    [3,6,9],
                    [3,5,7]]])

print(T1)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [3, 5, 7]]])


In [22]:
print(T1.ndim)
print(T1.shape)

3
torch.Size([1, 3, 3])


In [25]:
print(T1[0])
print(T1[0,0])
print(T1[0,0,0])

tensor([[1, 2, 3],
        [3, 6, 9],
        [3, 5, 7]])
tensor([1, 2, 3])
tensor(1)
